<!DOCTYPE html>
<html lang="es">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="GestorPortal">
    <meta name="author" content="GestorPortal">
    <meta name="generator" content="GestorPortal 1.0">
    <?= $this->headTitle('GestorPortal')->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- CSS -->
    <?=
    $this->headLink([
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/favicon.ico'
    ])
        ->prependStylesheet($this->basePath('css/sweetalert2-bootstrap-4.min.css'))
        ->prependStylesheet($this->basePath('css/all_fontawesome.min.css'));
    ?>
    <!-- JS -->
    <?=
    $this->headScript()
        ->prependFile($this->basePath('js/sweetalert2.min.js'), 'text/javascript')
        ->prependFile($this->basePath('js/feather.min.js'), 'text/javascript')
        ->prependFile($this->basePath('vendors/jquery/dist/jquery.min.js'), 'text/javascript');
    ?>
    <link href="cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <!-- Bootstrap -->
    <link href="<?= $this->basePath('vendors/bootstrap/dist/css/bootstrap.min.css'); ?>" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?= $this->basePath('vendors/font-awesome/css/font-awesome.min.css'); ?>" rel="stylesheet">
    <!-- NProgress -->
    <link href="<?= $this->basePath('vendors/nprogress/nprogress.css'); ?>" rel="stylesheet">
    <!-- FullCalendar -->
    <link href="<?= $this->basePath('vendors/fullcalendar/dist/fullcalendar.min.css'); ?>" rel="stylesheet">
    <link href="<?= $this->basePath('vendors/fullcalendar/dist/fullcalendar.print.css'); ?>" rel="stylesheet" media="print">
    <!-- Animate.css -->
    <link href="<?php echo $this->basePath('vendors/animate.css/animate.min.css'); ?>" rel="stylesheet">
    <!-- iCheck -->
    <link href="<?= $this->basePath('vendors/iCheck/skins/flat/green.css'); ?>" rel="stylesheet">
    <!-- Datatables -->
    <link href="<?= $this->basePath('vendors/datatables.net-bs/css/dataTables.bootstrap.min.css'); ?>" rel="stylesheet">
    <link href="<?= $this->basePath('vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css'); ?>" rel="stylesheet">
    <link href="<?= $this->basePath('vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css'); ?>" rel="stylesheet">
    <link href="<?= $this->basePath('vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css'); ?>" rel="stylesheet">
    <link href="<?= $this->basePath('vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css'); ?>" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="<?= $this->basePath('vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css'); ?>" rel="stylesheet">
    <!-- PNotify -->
    <link href="<?= $this->basePath('vendors/pnotify/dist/pnotify.css'); ?>" rel="stylesheet">
    <link href="<?= $this->basePath('vendors/pnotify/dist/pnotify.buttons.css'); ?>" rel="stylesheet">
    <link href="<?= $this->basePath('vendors/pnotify/dist/pnotify.nonblock.css'); ?>" rel="stylesheet">
    <!-- JQVMap -->
    <link href="<?= $this->basePath('vendors/jqvmap/dist/jqvmap.min.css'); ?>" rel="stylesheet" />
    <!-- bootstrap-daterangepicker -->
    <link href="<?= $this->basePath('vendors/bootstrap-daterangepicker/daterangepicker.css'); ?>" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="<?= $this->basePath('build/css/custom.css'); ?>" rel="stylesheet">

    <style>
        .estilologo {
            color: #000066;
            text-shadow: black 0.1em 0.1em 0.2em
        }
    </style>

</head>

<body class="nav-md">
    <?php
    $loginUsuario = 'SESION NO INICIADA';
    $auth = new Laminas\Authentication\AuthenticationService();
    if ($auth->hasIdentity()) {
        $infoSesion['login'] = $auth->getIdentity()->login;
        $infoSesion['usuario'] = $auth->getIdentity()->usuario;
        $infoSesion['foto'] = $auth->getIdentity()->foto;
    ?>
        <div class="container body">
            <div class="main_container">
                <div class="col-md-3 left_col">
                    <div class="left_col scroll-view">
                        <div class="navbar nav_title" style="border: 0;">
                            <a href="<?= $this->url('inicio') ?>" class="site_title"><img src="<?= $this->basePath('img/logo.png') ?>" width="50px" /> GestorPortal</a>
                        </div>

                        <div class="clearfix"></div>

                        <!-- menu profile quick info -->
                        <div class="profile clearfix">
                            <div class="profile_pic">
                                <img src="<?= $this->basePath('img/profile/') . $infoSesion['foto']; ?>" alt="..." class="img-circle profile_img">
                            </div>
                            <div class="profile_info">
                                <span>Bienvenido,</span>
                                <h2><?= $infoSesion['usuario'] ?></h2>
                            </div>
                        </div>
                        <!-- /menu profile quick info -->

                        <br />

                        <!-- sidebar menu -->
                        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                            <div class="menu_section">
                                <h3>General</h3>
                                <ul class="nav side-menu">
                                    <li><a href="<?= $this->url('inicio') ?>"><i class="fa fa-home"></i> INICIO</a></li>
                                    <li><a href="<?= $this->url('administracion/evento', array('controller' => 'evento', 'action' => 'index')) ?>"><i class="fa fa-calendar"></i> EVENTOS</a></li>
                                    <li><a href="<?= $this->url('administracion/solicitud', array('controller' => 'solicitud', 'action' => 'index')) ?>"><i class="fa fa-graduation-cap"></i> SOLICITUDES</a></li>
                                    <li><a href="<?= $this->url('administracion/archivo', array('controller' => 'archivo', 'action' => 'index')) ?>"><i class="fa fa-file-pdf-o"></i> ARCHIVOS</a></li>
                                    <li><a href="<?= $this->url('administracion/lumen', array('controller' => 'lumen', 'action' => 'index')) ?>"><i class="fa fa-files-o"></i> LUMEN</a></li>
                                    <li><a><i class="fa fa-users"></i> GESTOR USUARIOS <span class="fa fa-chevron-down"></span></a>
                                        <ul class="nav child_menu">
                                            <li><a href="<?= $this->url('usermanager/acceso', array('controller' => 'acceso', 'action' => 'index')) ?>">Accesos</a></li>
                                            <li><a href="<?= $this->url('usermanager/empleadocliente', array('controller' => 'empleadocliente', 'action' => 'index')) ?>">Usuarios</a></li>
                                            <li><a href="form_validation.html">Roles</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- /sidebar menu -->

                        <!-- /menu footer buttons -->
                        <div class="sidebar-footer hidden-small" style="color: #FFFFFF;">
                            <a data-toggle="tooltip" data-placement="top" title="Settings">
                                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" data-placement="top" title="Lock">
                                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
                            </a>
                            <a data-toggle="tooltip" style="color: #FFFFFF" data-placement="top" title="Cerrar Sessión" href="<?= $this->url('cerrarsesion') ?>">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                            </a>
                        </div>
                        <!-- /menu footer buttons -->
                    </div>
                </div>

                <!-- top navigation -->
                <div class="top_nav">
                    <div class="nav_menu">
                        <div class="nav toggle" style="color: #9D0311;">
                            <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                        </div>
                        <nav class="nav navbar-nav">
                            <ul class=" navbar-right">
                                <li class="nav-item dropdown open" style="padding-left: 15px;">
                                    <a href="javascript:;" class="user-profile dropdown-toggle" aria-haspopup="true" id="navbarDropdown" data-toggle="dropdown" aria-expanded="false">
                                        <img src="<?= $this->basePath('img/profile/') . $infoSesion['foto']; ?>" alt=""><?= substr($infoSesion['usuario'], 0, 15); ?>
                                    </a>
                                    <div class="dropdown-menu dropdown-usermenu pull-right" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="<?= $this->url('usermanager/perfil', array('controller' => 'perfil', 'action' => 'index')) ?>"><i class="fa fa-user pull-right"></i> Perfil</a>
                                        <a class="dropdown-item" href="javascript:;">
                                            <span class="badge bg-red pull-right">50%</span>
                                            <span>Settings</span>
                                        </a>
                                        <a class="dropdown-item" href="javascript:;">Help</a>
                                        <a class="dropdown-item" href="<?= $this->url('cerrarsesion') ?>"><i class="fa fa-sign-out pull-right" style="color:red;"></i> Cerrar Sessión</a>
                                    </div>
                                </li>

                                <li role="presentation" class="nav-item dropdown open">
                                    <a href="javascript:;" class="dropdown-toggle info-number" id="navbarDropdown1" data-toggle="dropdown" aria-expanded="false">
                                        <i class="fa fa-envelope-o"></i>
                                        <span class="badge bg-green">6</span>
                                    </a>
                                    <ul class="dropdown-menu list-unstyled msg_list" role="menu" aria-labelledby="navbarDropdown1">
                                        <li class="nav-item">
                                            <a class="dropdown-item">
                                                <span class="image"><img src="<?= $this->basePath('img/profile/perfilMujer.png'); ?>" alt="Profile Image" /></span>
                                                <span>
                                                    <span>Beatriz Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="dropdown-item">
                                                <span class="image"><img src="<?= $this->basePath('img/profile/perfilMujer.png'); ?>" alt="Profile Image" /></span>
                                                <span>
                                                    <span>Beatriz Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="dropdown-item">
                                                <span class="image"><img src="<?= $this->basePath('img/profile/perfilMujer.png'); ?>" alt="Profile Image" /></span>
                                                <span>
                                                    <span>Beatriz Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="dropdown-item">
                                                <span class="image"><img src="<?= $this->basePath('img/profile/perfilMujer.png'); ?>" alt="Profile Image" /></span>
                                                <span>
                                                    <span>Beatriz Smith</span>
                                                    <span class="time">3 mins ago</span>
                                                </span>
                                                <span class="message">
                                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                                </span>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <div class="text-center">
                                                <a class="dropdown-item">
                                                    <strong>See All Alerts</strong>
                                                    <i class="fa fa-angle-right"></i>
                                                </a>
                                            </div>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </nav>
                    </div>
                </div>
                <!-- /top navigation -->

                <!-- page content -->
                <div class="right_col" role="main">
                    <?= $this->content ?>
                </div>
                <!-- /page content -->

                <!-- footer content -->
                <footer>
                    <div class="pull-right">
                        <p><small>División TIC &copy; Copyright 2023</small></p>
                    </div>
                    <div class="clearfix"></div>
                </footer>
                <!-- /footer content -->
            </div>
        </div>


    <?php } else { ?>
        <div class="container body">
            <div class="main_container">
                <!-- page content -->
                <div class="col-md-12" style="color:#FFFFFF;">
                    <div class="col-middle">
                        <div class="text-center text-center">
                            <a href="https://www.unicauca.edu.co" target="_blank"><img class="animated bounce hvr-buzz estilologo" src="<?= $this->basePath('img/logo.png') ?>" /></a>
                            <p style="color: #FFFFFF;"><b>Universidad del Cauca</b></p>
                            <h1 class="error-number">404</h1>
                            <h2>Lo sentimos pero no pudimos encontrar esta página.</h2>
                            <p>Esta página que estás buscando no existe <a href="/gestorportal" style="color:#9D0311;">&iquest;Ir al inicio&quest;</a>
                            </p>
                            <p><small>División TIC &copy; Copyright 2023</small></p>
                            <div class="mid_center">
                                <h3>Buscar</h3>
                                <form>
                                    <div class="  form-group pull-right top_search">
                                        <div class="input-group">
                                            <input type="text" class="form-control" placeholder="Buscar...">
                                            <span class="input-group-btn">
                                                <button class="btn btn-secondary" type="button"><i class="fa fa-search"></i></button>
                                            </span>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /page content -->
            </div>
        </div>
    <?php } ?>
    <script>
        feather.replace()
    </script>
    <!-- Bootstrap -->
    <script src="<?= $this->basePath('vendors/bootstrap/dist/js/bootstrap.bundle.min.js'); ?>"></script>
    <!-- FastClick -->
    <script src="<?= $this->basePath('vendors/fastclick/lib/fastclick.js'); ?>"></script>
    <!-- NProgress -->
    <script src="<?= $this->basePath('vendors/nprogress/nprogress.js'); ?>"></script>
    <!-- FullCalendar -->
    <script src="<?= $this->basePath('vendors/moment/min/moment.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/fullcalendar/dist/fullcalendar.min.js'); ?>"></script>
    <script src="<?= $this->basePath('js/fullcalendar_3.1.0_locale-all.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/fullcalendar/dist/lang/es.js'); ?>"></script>
    <!-- Chart.js -->
    <script src="<?= $this->basePath('vendors/Chart.js/dist/Chart.min.js'); ?>"></script>
    <!-- gauge.js -->
    <script src="<?= $this->basePath('vendors/gauge.js/dist/gauge.min.js'); ?>"></script>
    <!-- bootstrap-progressbar -->
    <script src="<?= $this->basePath('vendors/bootstrap-progressbar/bootstrap-progressbar.min.js'); ?>"></script>
    <!-- iCheck -->
    <script src="<?= $this->basePath('vendors/iCheck/icheck.min.js'); ?>"></script>
    <!-- PNotify -->
    <script src="<?php echo $this->basePath('vendors/pnotify/dist/pnotify.js'); ?>"></script>
    <script src="<?php echo $this->basePath('vendors/pnotify/dist/pnotify.buttons.js'); ?>"></script>
    <script src="<?php echo $this->basePath('vendors/pnotify/dist/pnotify.nonblock.js'); ?>"></script>
    <!-- Datatables -->
    <script src="<?= $this->basePath('vendors/datatables.net/js/jquery.dataTables.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-bs/js/dataTables.bootstrap.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-buttons/js/dataTables.buttons.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-buttons/js/buttons.flash.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-buttons/js/buttons.html5.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-buttons/js/buttons.print.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-keytable/js/dataTables.keyTable.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-responsive/js/dataTables.responsive.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/datatables.net-scroller/js/dataTables.scroller.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/jszip/dist/jszip.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/pdfmake/build/pdfmake.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/pdfmake/build/vfs_fonts.js'); ?>"></script>
    <!-- Skycons -->
    <script src="<?= $this->basePath('vendors/skycons/skycons.js'); ?>"></script>
    <!-- Flot -->
    <script src="<?= $this->basePath('vendors/Flot/jquery.flot.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/Flot/jquery.flot.pie.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/Flot/jquery.flot.time.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/Flot/jquery.flot.stack.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/Flot/jquery.flot.resize.js'); ?>"></script>
    <!-- Flot plugins -->
    <script src="<?= $this->basePath('vendors/flot.orderbars/js/jquery.flot.orderBars.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/flot-spline/js/jquery.flot.spline.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/flot.curvedlines/curvedLines.js'); ?>"></script>
    <!-- DateJS -->
    <script src="<?= $this->basePath('vendors/DateJS/build/date.js'); ?>"></script>
    <!-- JQVMap -->
    <script src="<?= $this->basePath('vendors/jqvmap/dist/jquery.vmap.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/jqvmap/dist/maps/jquery.vmap.world.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/jqvmap/examples/js/jquery.vmap.sampledata.js'); ?>"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="<?= $this->basePath('vendors/moment/min/moment.min.js'); ?>"></script>
    <script src="<?= $this->basePath('vendors/bootstrap-daterangepicker/daterangepicker.js'); ?>"></script>

    <!-- Custom Theme Scripts -->
    <script src="<?= $this->basePath('build/js/custom.js'); ?>"></script>

</body>

</html>